apiVersion: batch/v1
kind: Job
metadata:
  name: nats-push-reader
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: reader
          image: "kast-registry:30005/nats-tester:latest"
          imagePullPolicy: Always
          args:
            - reader
            - -s
            - nats.default:4222
            - --max-listening-sessions
            - 3
