apiVersion: batch/v1
kind: Job
metadata:
  name: nats-writer
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: writer
          image: "kast-registry:30005/nats-tester:latest"
          imagePullPolicy: IfNotPresent
          args:
            - writer
            - -n
            - "1000"
            - -s
            - nats.default:4222
